### ISSUE TITLE
Example - incorrect syntax

### ISSUE THREAD

**Issue by Julie-House** [byunguk/jira-issue-type#1]
When using this action in my workflow, it failed to transition my task because it attempted to put it into a transition that doesn't exist for that type. Turns out, the documented `if` statement syntax is wrong.

` if: ${{ steps.issuetype.outputs.name == 'Story' }}`

Should actually be
` if: steps.issuetype.outputs.name == 'Story'`

**Comment by byunguk** [comment]
Thank you for the report. Actually I haven't checked the case when if condition has only one condition.
My case has multiple conditions and it worked for me. But I'll check that case.

**Comment by byunguk** [comment]
@Julie-House You're right. I guess syntax was changed. I updated readme file. Closing the issue.
